---
version: 2.1
executors:
  toxandnode:
    working_directory: ~/project
    docker:
      - image: girder/tox-and-node
commands:
  tox:
    description: "Run tox"
    parameters:
      env:
        type: string
    steps:
      - run:
          name: Run tests via tox
          command: tox -e << parameters.env >> | cat; test ${PIPESTATUS[0]} -eq 0
jobs:
  lintclient:
    executor: toxandnode
    steps:
      - checkout
      - tox:
          env: lintclient

workflows:
  version: 2
  ci:
    jobs:
      - lintclient
